/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoglalasRouteImport } from './routes/foglalas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoglalasRoute = FoglalasRouteImport.update({
  id: '/foglalas',
  path: '/foglalas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foglalas': typeof FoglalasRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foglalas': typeof FoglalasRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foglalas': typeof FoglalasRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/foglalas' | '/galeria' | '/kontakt' | '/rolam' | '/szolgaltatasok'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foglalas' | '/galeria' | '/kontakt' | '/rolam' | '/szolgaltatasok'
  id:
    | '__root__'
    | '/'
    | '/foglalas'
    | '/galeria'
    | '/kontakt'
    | '/rolam'
    | '/szolgaltatasok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoglalasRoute: typeof FoglalasRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  RolamRoute: typeof RolamRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foglalas': {
      id: '/foglalas'
      path: '/foglalas'
      fullPath: '/foglalas'
      preLoaderRoute: typeof FoglalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoglalasRoute: FoglalasRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  RolamRoute: RolamRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
