/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArlistaRouteImport } from './routes/arlista'
import { Route as EskuvoiFotozasRouteImport } from './routes/eskuvoi-fotozas'
import { Route as FoglalasRouteImport } from './routes/foglalas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KozmetikaiKezelesekRouteImport } from './routes/kozmetikai-kezelesek'
import { Route as KozmetikaiKezelesekIndexRouteImport } from './routes/kozmetikai-kezelesek.index'
import { Route as KozmetikaiKezelesekCategoryRouteImport } from './routes/kozmetikai-kezelesek.$category'
import { Route as KozmetikaiKezelesekCategoryIndexRouteImport } from './routes/kozmetikai-kezelesek.$category.index'
import { Route as KozmetikaiKezelesekCategoryTreatmentRouteImport } from './routes/kozmetikai-kezelesek.$category.$treatment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArlistaRoute = ArlistaRouteImport.update({
  id: '/arlista',
  path: '/arlista',
  getParentRoute: () => rootRouteImport,
} as any)
const EskuvoiFotozasRoute = EskuvoiFotozasRouteImport.update({
  id: '/eskuvoi-fotozas',
  path: '/eskuvoi-fotozas',
  getParentRoute: () => rootRouteImport,
} as any)
const FoglalasRoute = FoglalasRouteImport.update({
  id: '/foglalas',
  path: '/foglalas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KozmetikaiKezelesekRoute = KozmetikaiKezelesekRouteImport.update({
  id: '/kozmetikai-kezelesek',
  path: '/kozmetikai-kezelesek',
  getParentRoute: () => rootRouteImport,
} as any)
const KozmetikaiKezelesekIndexRoute =
  KozmetikaiKezelesekIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => KozmetikaiKezelesekRoute,
  } as any)
const KozmetikaiKezelesekCategoryRoute =
  KozmetikaiKezelesekCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => KozmetikaiKezelesekRoute,
  } as any)
const KozmetikaiKezelesekCategoryIndexRoute =
  KozmetikaiKezelesekCategoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => KozmetikaiKezelesekCategoryRoute,
  } as any)
const KozmetikaiKezelesekCategoryTreatmentRoute =
  KozmetikaiKezelesekCategoryTreatmentRouteImport.update({
    id: '/$treatment',
    path: '/$treatment',
    getParentRoute: () => KozmetikaiKezelesekCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/eskuvoi-fotozas': typeof EskuvoiFotozasRoute
  '/foglalas': typeof FoglalasRoute
  '/kontakt': typeof KontaktRoute
  '/kozmetikai-kezelesek': typeof KozmetikaiKezelesekRouteWithChildren
  '/kozmetikai-kezelesek/$category': typeof KozmetikaiKezelesekCategoryRouteWithChildren
  '/kozmetikai-kezelesek/': typeof KozmetikaiKezelesekIndexRoute
  '/kozmetikai-kezelesek/$category/$treatment': typeof KozmetikaiKezelesekCategoryTreatmentRoute
  '/kozmetikai-kezelesek/$category/': typeof KozmetikaiKezelesekCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/eskuvoi-fotozas': typeof EskuvoiFotozasRoute
  '/foglalas': typeof FoglalasRoute
  '/kontakt': typeof KontaktRoute
  '/kozmetikai-kezelesek': typeof KozmetikaiKezelesekIndexRoute
  '/kozmetikai-kezelesek/$category/$treatment': typeof KozmetikaiKezelesekCategoryTreatmentRoute
  '/kozmetikai-kezelesek/$category': typeof KozmetikaiKezelesekCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arlista': typeof ArlistaRoute
  '/eskuvoi-fotozas': typeof EskuvoiFotozasRoute
  '/foglalas': typeof FoglalasRoute
  '/kontakt': typeof KontaktRoute
  '/kozmetikai-kezelesek': typeof KozmetikaiKezelesekRouteWithChildren
  '/kozmetikai-kezelesek/$category': typeof KozmetikaiKezelesekCategoryRouteWithChildren
  '/kozmetikai-kezelesek/': typeof KozmetikaiKezelesekIndexRoute
  '/kozmetikai-kezelesek/$category/$treatment': typeof KozmetikaiKezelesekCategoryTreatmentRoute
  '/kozmetikai-kezelesek/$category/': typeof KozmetikaiKezelesekCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arlista'
    | '/eskuvoi-fotozas'
    | '/foglalas'
    | '/kontakt'
    | '/kozmetikai-kezelesek'
    | '/kozmetikai-kezelesek/$category'
    | '/kozmetikai-kezelesek/'
    | '/kozmetikai-kezelesek/$category/$treatment'
    | '/kozmetikai-kezelesek/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arlista'
    | '/eskuvoi-fotozas'
    | '/foglalas'
    | '/kontakt'
    | '/kozmetikai-kezelesek'
    | '/kozmetikai-kezelesek/$category/$treatment'
    | '/kozmetikai-kezelesek/$category'
  id:
    | '__root__'
    | '/'
    | '/arlista'
    | '/eskuvoi-fotozas'
    | '/foglalas'
    | '/kontakt'
    | '/kozmetikai-kezelesek'
    | '/kozmetikai-kezelesek/$category'
    | '/kozmetikai-kezelesek/'
    | '/kozmetikai-kezelesek/$category/$treatment'
    | '/kozmetikai-kezelesek/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArlistaRoute: typeof ArlistaRoute
  EskuvoiFotozasRoute: typeof EskuvoiFotozasRoute
  FoglalasRoute: typeof FoglalasRoute
  KontaktRoute: typeof KontaktRoute
  KozmetikaiKezelesekRoute: typeof KozmetikaiKezelesekRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arlista': {
      id: '/arlista'
      path: '/arlista'
      fullPath: '/arlista'
      preLoaderRoute: typeof ArlistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eskuvoi-fotozas': {
      id: '/eskuvoi-fotozas'
      path: '/eskuvoi-fotozas'
      fullPath: '/eskuvoi-fotozas'
      preLoaderRoute: typeof EskuvoiFotozasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foglalas': {
      id: '/foglalas'
      path: '/foglalas'
      fullPath: '/foglalas'
      preLoaderRoute: typeof FoglalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kozmetikai-kezelesek': {
      id: '/kozmetikai-kezelesek'
      path: '/kozmetikai-kezelesek'
      fullPath: '/kozmetikai-kezelesek'
      preLoaderRoute: typeof KozmetikaiKezelesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kozmetikai-kezelesek/': {
      id: '/kozmetikai-kezelesek/'
      path: '/'
      fullPath: '/kozmetikai-kezelesek/'
      preLoaderRoute: typeof KozmetikaiKezelesekIndexRouteImport
      parentRoute: typeof KozmetikaiKezelesekRoute
    }
    '/kozmetikai-kezelesek/$category': {
      id: '/kozmetikai-kezelesek/$category'
      path: '/$category'
      fullPath: '/kozmetikai-kezelesek/$category'
      preLoaderRoute: typeof KozmetikaiKezelesekCategoryRouteImport
      parentRoute: typeof KozmetikaiKezelesekRoute
    }
    '/kozmetikai-kezelesek/$category/': {
      id: '/kozmetikai-kezelesek/$category/'
      path: '/'
      fullPath: '/kozmetikai-kezelesek/$category/'
      preLoaderRoute: typeof KozmetikaiKezelesekCategoryIndexRouteImport
      parentRoute: typeof KozmetikaiKezelesekCategoryRoute
    }
    '/kozmetikai-kezelesek/$category/$treatment': {
      id: '/kozmetikai-kezelesek/$category/$treatment'
      path: '/$treatment'
      fullPath: '/kozmetikai-kezelesek/$category/$treatment'
      preLoaderRoute: typeof KozmetikaiKezelesekCategoryTreatmentRouteImport
      parentRoute: typeof KozmetikaiKezelesekCategoryRoute
    }
  }
}

interface KozmetikaiKezelesekCategoryRouteChildren {
  KozmetikaiKezelesekCategoryTreatmentRoute: typeof KozmetikaiKezelesekCategoryTreatmentRoute
  KozmetikaiKezelesekCategoryIndexRoute: typeof KozmetikaiKezelesekCategoryIndexRoute
}

const KozmetikaiKezelesekCategoryRouteChildren: KozmetikaiKezelesekCategoryRouteChildren =
  {
    KozmetikaiKezelesekCategoryTreatmentRoute:
      KozmetikaiKezelesekCategoryTreatmentRoute,
    KozmetikaiKezelesekCategoryIndexRoute:
      KozmetikaiKezelesekCategoryIndexRoute,
  }

const KozmetikaiKezelesekCategoryRouteWithChildren =
  KozmetikaiKezelesekCategoryRoute._addFileChildren(
    KozmetikaiKezelesekCategoryRouteChildren,
  )

interface KozmetikaiKezelesekRouteChildren {
  KozmetikaiKezelesekCategoryRoute: typeof KozmetikaiKezelesekCategoryRouteWithChildren
  KozmetikaiKezelesekIndexRoute: typeof KozmetikaiKezelesekIndexRoute
}

const KozmetikaiKezelesekRouteChildren: KozmetikaiKezelesekRouteChildren = {
  KozmetikaiKezelesekCategoryRoute:
    KozmetikaiKezelesekCategoryRouteWithChildren,
  KozmetikaiKezelesekIndexRoute: KozmetikaiKezelesekIndexRoute,
}

const KozmetikaiKezelesekRouteWithChildren =
  KozmetikaiKezelesekRoute._addFileChildren(KozmetikaiKezelesekRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArlistaRoute: ArlistaRoute,
  EskuvoiFotozasRoute: EskuvoiFotozasRoute,
  FoglalasRoute: FoglalasRoute,
  KontaktRoute: KontaktRoute,
  KozmetikaiKezelesekRoute: KozmetikaiKezelesekRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
